### ISSUE TITLE
Add ability to teardown listeners and dom nodes

### ISSUE THREAD

**Issue by xcskier56** [BoxFactura/pulltorefresh.js#10]
First off, I want to say that I really like this project. As you've stated, your goal is to make it as easy as possible, and I think you've achieved that. 

However, before I can implement this in production, I'd like a way to ensure that when we change pages in a SPA like ember or angular, we are able to teardown the listeners and bindings properly and free up memory. To me this would be a function that is returned that holds references to the listeners and created dom nodes and then that function can teardown and remove them. 

I've created a work in progress that demonstrates what I think this would look like. Basically, init returns an object with a function `destroy` that should remove all bindings and whatnot. 

I've submitted a PR for this functionality, which I consider a work in progress. If you're interested in adding this feature, I'd appreciate your feedback on the PR to make it as good as possible.

Thanks

**Comment by pateketrueke** [comment]
I totally agree, I reviewed your PR and I think it's ready to merge.
