### ISSUE TITLE
Not working properly on iOS Safari

### ISSUE THREAD

**Issue by diegoiglesias** [BoxFactura/pulltorefresh.js#101]
**Current behavior:**
Looks like it's not being triggered when scroll is not completely stopped.

**Expected behavior:**
Pulltorefresh must be triggered when user scroll downs, even when scroll comes from the bottom

**URL for demo with bug:**
Just try the [demo page ](https://www.boxfactura.com/pulltorefresh.js/demos/basic.html)on iOS Safari as shown on the next video
https://streamable.com/y5a6v9

**Browsers affected:**
iOS 14.2 Safari

**Comment by faelsoto** [comment]
> Pulltorefresh must be triggered when user scroll downs, even when scroll comes from the bottom

This is actually what happens, just try it yourself. What seems to be happening is that Safari's bounce is throwing off calculations. Feel free to open a PR if you have some ideas on how to fix it.

**Comment by PlippiePlop** [comment]
HI, One way is the prevent the ios pull on using these settings on the body:
`body{
 touch-action: none;
    overscroll-behavior-y: contain;
}
`

**Note:** You need the event triggerElement something else than the body element. For example the page header.
