### ISSUE TITLE
onReset: TypeError null is not an object (evaluating 'handler.ptrElement.classList') 

### ISSUE THREAD

**Issue by piwel** [BoxFactura/pulltorefresh.js#102]
Hi

Because of the `setTimeout` just below, it may happen that handler is already null when trying to reset it.

It would be safer to check that `ptrElement` is not null before changing `classList` and `style`.

https://github.com/BoxFactura/pulltorefresh.js/blob/c674942b1f171129cef3fd0343acd446e300abfe/dist/index.umd.js#L71-L78

**Comment by pateketrueke** [comment]
Could you provide that change back in code? If it passes our test-suite I think it'll be fine, thank you!

**Comment by piwel** [comment]
https://github.com/BoxFactura/pulltorefresh.js/pull/103

**Comment by armadillo-dev** [comment]
@pateketrueke, I saw your commit https://github.com/BoxFactura/pulltorefresh.js/commit/3b4e7561ea51ab6bc91bd2b1250ccaaddc074e27
But it seems to be not yet shipped npm package(https://www.npmjs.com/package/pulltorefreshjs)
So I still seen `Cannot read property 'classList' of null` error in sentry.

Could you please publish this commit?

**Comment by pateketrueke** [comment]
> Could you please publish this commit?

Yeah, no problem.
