### ISSUE TITLE
Does not work when body has been changed

### ISSUE THREAD

**Issue by jarmo** [BoxFactura/pulltorefresh.js#108]
# Bug report

I'm using a library called [morphdom](https://github.com/patrick-steele-idem/morphdom) to patch document.body with new contents on navigation to different pages. It seesm that after doing this then pulltorefresh stops working or misbehaves. I've tried calling `destroy` or `destroyAll` before patching and `init` afterwards, but it doesn't seem to make any difference.

Is it possible that pulltorefresh does not destroy itself properly thus making it unable to re-initialize?

**Comment by faelsoto** [comment]
I don't think any library will persist when you change the DOM, as the events, properties and markup will change. Maybe you can try initializing ptr.js on every DOM change.

Also, please keep the template to report a bug.

**Comment by jarmo** [comment]
Thank you for your reply!

However, this doesn't solve the problem. Reading the things you say then I can assume that `destroy` and `destroyAll` functions do not clean up properly and there is still some state somewhere, which will mess things up. This implies that these functions do not work as expected or I am missing something.

There's no reasonable way for me to re-initialize ptr.js again since it is installed into `node_modules` and packaged as a bigger bundle with every other vendor library.

Are you implying that while initializing ptr.js then some global state will be persisted before calling `init`?

I tried to understand by looking into the library code, but couldn't see at first glance anything which might be the culprit.

Any help would be appreciated and sorry for not keeping the bug report template.

**Comment by faelsoto** [comment]
If you found what you believe it's a bug, feel free to create a PR, explain your case and we'll review it.
