### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by arslan752** [BoxFactura/pulltorefresh.js#121]
When you click on page it shows this error:
Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at _handler.contains (pulltorefresh.js?1603855390480:355:38)
    at pulltorefresh.js?1603855390480:134:68
    at Array.filter (<anonymous>)
    at _onTouchStart (pulltorefresh.js?1603855390480:134:37)

**Comment by pateketrueke** [comment]
Thanks for submitting your issue, you don't have a repro so we can look at it?

**Comment by faelsoto** [comment]
I'm going to close this one as the issue template was totally ignored. Feel free to open a new one but make sure you include all the information required so we can take a look at the issue.
