### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by benjaminfaustinotiks** [BoxFactura/pulltorefresh.js#126]
# Bug report

**Current behavior:**

Refresh the page -> click Profile -> Error triggered

**Browsers affected:**

Google Chrome

IMAGES PROVIDED

![Screenshot from 2023-08-24 11-28-49](https://github.com/BoxFactura/pulltorefresh.js/assets/72246951/ca296ef9-1e70-4509-8a76-0dfaa4d6dca3)

![Screenshot from 2023-08-24 11-23-51](https://github.com/BoxFactura/pulltorefresh.js/assets/72246951/365931d2-c9ed-4271-a9ea-d20e71d6a464)

FILE 
dist > index.js
![Screenshot from 2023-08-24 11-26-23](https://github.com/BoxFactura/pulltorefresh.js/assets/72246951/8acd4ca6-bbaa-4e8c-9bf6-83d44c4c856a)

**Comment by faelsoto** [comment]
Please fill in all the required information in the template. The images are not helping much to detect the issue. Feel free to open a new issue when you can provide all the required information.
