### ISSUE TITLE
works in browser - but not when 'added to homescreen'

### ISSUE THREAD

**Issue by wdiechmann** [BoxFactura/pulltorefresh.js#130]
# Bug report
**disclaimer** Not sure if it is a bug - perhaps iOS does not afford this 'feature'

When I go to an endpoint with the pulltorefresh.js 'live' in a browser (on my iPhone) it works as announced - but when I add the URL to my homescreen, in effect making the URL an 'app' of sorts, and then close my browser (Safari) and open the 'app' and retry the pull effect nothing happens - not even the _pull down to refresh_ element gets visible

I've tried it on Polypane too - it works as announced (but I'm not sure if Polypane is able to emulate the iPhone 100%)

My apologies if I've misinterpreted the announced effect

**Current behavior:**

**Expected behavior:**

**JSFiddle URL for demo with bug:**

**Browsers affected:**
at least Chrome, Firefox, Safari on iPhone -

**Comment by crusy** [comment]
I'll do the same; using PtR in a "Home Screen App" (aka Progressive Web App), and it works.

PS: Without a demo I guess this issue will be closed pretty soon ...

**Comment by faelsoto** [comment]
Without some code or anything to grab on this is only hearsay, and there's not much we can do about it. My recommendation would be to debug it through the emulator.

**Comment by salomvary** [comment]
Hi folks!

I've tried using `pulltorefresh.js` to re-enable pull-to-refresh in an iOS progressive web app (PWA) and found it to mostly not be working. It seems to be working on the firs page load, but when navigating between the pages within the PWA, it stops working.

Steps to reproduce (needs XCode and Simulator, also works on real iOS devices, the dev server URL needs tweaking in that case):

- Clone my fork that adds PWA capability to the demo: https://github.com/BoxFactura/pulltorefresh.js/pull/131
- Start the dev server as described here: https://github.com/BoxFactura/pulltorefresh.js?tab=readme-ov-file#contribute
- Open an iOS device in the Simulator (tested with iPhone with iOS 26 and iOS 18)
- Open Safari in iOS
- Open http://127.0.0.1:8080/raw.html in Safari
- Go to '...' / Share / the _second_ '... more' option / Add to home screen
- Open the PTR Demo app from the home screen
- Pull down, pull-to-refresh is likely going to work
- Click "Basic"
- Pull down, pull-to-refresh is likely **not** going to work
- Click "Raw"
- Pull down, pull-to-refresh is likely **not** going to work
- When switching between pages within the app, pull-to-refresh sometimes works, sometimes does not. Mostly does not in my experience.

I've also done a bit of basic debugging and it seems like the `touch*` events are simply not triggered (while `scroll` does). There is no other error or obvious sign of problem. I also do not yet have an idea why this might be happening.

Similar problems elsewhere:

- https://developer.apple.com/forums/thread/682171
- https://bugs.webkit.org/show_bug.cgi?id=176454
- https://www.reddit.com/r/webdev/comments/xyzma9/safari_16_on_ios_not_firing_some_touch_events_on/

Shall we reopen this issues @faelsoto ?
