### ISSUE TITLE
v0.1.3 is not on npm

### ISSUE THREAD

**Issue by rlebosse** [BoxFactura/pulltorefresh.js#14]
The latest version of pulltorefreshjs on npm is **0.1.1** : [https://www.npmjs.com/package/pulltorefreshjs](https://www.npmjs.com/package/pulltorefreshjs)

Could you publish version **0.1.3** ?

**Comment by pateketrueke** [comment]
Solved! :tada:

**Comment by rlebosse** [comment]
Faster than light! Thanks a lot for your reactivity and this awesome library
