### ISSUE TITLE
sometimes the _onTouchEnd event not trigger

### ISSUE THREAD

**Issue by lishichao1002** [BoxFactura/pulltorefresh.js#16]
I use the pulltorefresh.js lib, and find a bug. Sometimes the _onTouchEnd event not trigger so the page don't repaint. I'm not sure is there a bug or the way i use is not correct.
https://code.google.com/p/android/issues/detail?id=19827
http://blog.mobiscroll.com/working-with-touch-events/

![image](https://cloud.githubusercontent.com/assets/13584162/23603158/d56efe3e-028e-11e7-92c7-a154400f3ceb.png)
![image](https://cloud.githubusercontent.com/assets/13584162/23603176/e0f18e20-028e-11e7-9ae2-a872dcde1c16.png)
![image](https://cloud.githubusercontent.com/assets/13584162/23603185/eae37114-028e-11e7-8ff7-4ec7e2602730.png)
![image](https://cloud.githubusercontent.com/assets/13584162/23603197/f9ffeca4-028e-11e7-893d-2b9b2e81657c.png)
![image](https://cloud.githubusercontent.com/assets/13584162/23603200/fbd4a074-028e-11e7-9891-ac32b67f029d.png)

the console is not print. the page is not repaint.
the page address: http://test.platform.gamebean.net/bbs/default/index.html#/post_detail/daf50f86-54d7-440a-8c02-792adf68be77

**Comment by faelsoto** [comment]
Hello

I'm not quite familiar with Angular, so I can't help you debug. But what I can see is that you're initializing the plugin each time the `link` function is triggered. Maybe you could debug the lib's setup event to see if it's initializing.

Also, you're not setting the init parameters correctly, the plugin expects an element to prepend the pull to refresh instructions. Please refer to the docs and the demos, I'd suggest you to create a basic angular app to test this lib.

**Comment by lishichao1002** [comment]
Thanks a lot

I'm going crazy. I can't explain why it sometimes good sometimes bad. Today I do a lot test with angular and without angular, all it works. Maybe I need more time to positioning problem.

the angular directive is there.
```
(function (angular) {
    angular
        .module('ourpalm-util-pulltorefresh', [])

        .factory('OurpalmPullToFresh', function () {
            function OurpalmPullToFresh(opts) {
                var options = { };
                angular.extend(options, opts);
                this.getOptions = function () {
                    return options;
                }
            }

            return OurpalmPullToFresh;
        })
        .directive('ourpalmPullToRefresh', function ($timeout) {
            return {
                restrict: 'A',
                scope: {
                    ourpalmPullToRefresh: '='
                },
                link: function ($scope, $element, $attrs) {
                    let ele = $element[0], targetConfig = {mainElement: ele}, userConfig = $scope.ourpalmPullToRefresh;
                    angular.extend(targetConfig, userConfig ? userConfig.getOptions() : {});
                    let onRefresh = targetConfig.onRefresh;
                    targetConfig.onRefresh = function () {
                        $timeout(function () {
                            onRefresh();
                        });
                    };
                    let pullToRefresh = PullToRefresh.init(targetConfig);
                    $scope.$on('$destroy', function () {
                        pullToRefresh.destroy();
                    });
                }
            }
        })
})(angular);
```

I made an online example, hope to help more people.
http://runjs.cn/code/ttbhpg0n

**Comment by faelsoto** [comment]
I'm closing the issue as it might not be related directly with pulltorefresh.
