### ISSUE TITLE
Minify pulltorefresh.js

### ISSUE THREAD

**Issue by programmer5000-com** [BoxFactura/pulltorefresh.js#17]
Minify pulltorefresh.js for better performance.

**Comment by pateketrueke** [comment]
IMO minification doesn't add any performance, it save bytes only.

I totally agree with you: we lacks of proper minification so I think we can accept a PR for that or just wait until the next release.

Thanks for your feedback!

**Comment by faelsoto** [comment]
@programmer5000-com as @pateketrueke says, we do appreciate PRs!
