### ISSUE TITLE
mainElement is not defined

### ISSUE THREAD

**Issue by seven1986** [BoxFactura/pulltorefresh.js#20]
when I use pulltorefresh.min.js 
pull down is OK! 
But scrolling up will have errors 
![image](https://user-images.githubusercontent.com/20808494/27723679-db5dac56-5da0-11e7-8b37-f9914273346b.png)

![image](https://user-images.githubusercontent.com/20808494/27723784-439a68b8-5da1-11e7-850c-b4a266be34cb.png)

When I use I use pulltorefresh.js , every thing is OK.

I think the min.js may have some errors?

**Comment by pateketrueke** [comment]
Very interesting, I just rebuild locally and now the minified file is fine. 🔥 

I'm releasing a quick-patch for this, thanks for your feedback!

**Comment by pateketrueke** [comment]
BTW; I noticed your PR but I don't understand your solution, also you rebuilt everything?

That's an issue, because you exported the module as variable, and it should be as UMD for major compatibility.

Released as `0.1.5` :tada:

**Comment by seven1986** [comment]
Just use this awesome plugin in hurry. thanks!
