### ISSUE TITLE
NPM module has no export

### ISSUE THREAD

**Issue by benzittlau** [BoxFactura/pulltorefresh.js#21]
It looks like in the upgrade to 0.14 the NPM module no longer has an export in it, but instead just defines a variable:

https://github.com/BoxFactura/pulltorefresh.js/commit/bc3adb3febbb611862bcddf7c9edb34fc1227a78#diff-43757bd0eb07f11dd4e8e579643e30eb

Consequently if I attempt to import the module doing something like this:

```
let ptrjs = require('pulltorefreshjs');
```

ptrjs will be undefined.

**Comment by benzittlau** [comment]
Confirmed that using version `0.1.3` properly exports the module.

**Comment by pateketrueke** [comment]
Yeah, totally missed it.

I've published `0.1.6` for solving this.

Thanks for your feedback, sorry for publishing broke stuff. 🤖
