### ISSUE TITLE
Correct way to destroy?

### ISSUE THREAD

**Issue by ChrisHonniball** [BoxFactura/pulltorefresh.js#22]
I'm using this as a "pull to close" in an ember application and need to be able to tear it down and reinitialize. What's the correct way to do this? Currently, I'm doing this... Comments added to clarify if you don't have Ember experience.

```javascript
export default Ember.Component.extend({
	// Inserts HTML component/element
	didInsertElement() {
		const refresher = PullToRefresh.init({
			mainElement: 'body',
			instructionsPullToRefresh: 'Pull to Close',
			instructionsReleaseToRefresh: 'Release to Close',
			instructionsRefreshing: 'Closing...',
			onRefresh: () => {
				// Triggers applicatoin navigation where the refresh element is no longer needed and is removed firing the `willDestroyElement` hook
				this.attrs.pullAction();
			}
		});
		
		// Just a holder inside the component.
		this.set('refresher', refresher);
	},
	
	// Triggered when the application removes the component/element
	willDestroyElement() {
		// I've also tried `PullToRefresh.destroy()` here.
		this.get('refresher').destroy();
	}
});
```

**Comment by pateketrueke** [comment]
That code is suppossed to be working, the `init()` method will return an object with `{ destroy() { ... } }` as callback, is not working for you?

PS: there is no `PullToRefresh.destroy()` method on the current API.

**Comment by ChrisHonniball** [comment]
>the `init()` method will return an object with `{ destroy() { ... } }` as callback

I noticed that after reading through the code. 👍 

I managed to get it to work by changing the timing a little inside the application however I still the following console error if I have it run _instantly_:

```
Uncaught TypeError: Cannot read property 'classList' of undefined
    at onReset (pulltorefresh.js:97)
    at pulltorefresh.js:200
```

After this error fires the plugin refuses to re-init. However, if I run it on a short delay of 100ms I get it work properly without the error. I assume it's because the application removes the element from the DOM too quickly and causes the issue (just a guess).

**Comment by pateketrueke** [comment]
Yeah, the `onReset` callback should be fired after the user release the PTR, but after some timeout.

Such error happen If you call `destroy()` before the callback succeded.

I think we can remove any pending timers before destroy... that way you not longer need an additional timeout to workaround this.
