### ISSUE TITLE
only use on certain trigger divs

### ISSUE THREAD

**Issue by nickcom** [BoxFactura/pulltorefresh.js#24]
Great plugin. 

Just wondering how I can selectively target multiple containers to have this functionality.

Lets say my app has a UI as follows:
page 1) landing page with a list of products
page 2) detail view of list of products (open when user clicks on list from page 1)
page3) list of colour options for the product (opened from a button within page 2)

Lets say I want the pulltorefresh function on the list in page 1 and in page 3, but it shouldn't work on page 2.

I can't seem to enter multiple selectors in the ```mainElement``` option. I also notice multiple css tags are ignored (for example setting ```mainElement: 'body.page1, body.page2'``` doesn't work.

**Comment by faelsoto** [comment]
Hey!

That seems like a very specific use case that can be solved by adding a class to those pages, rather than using multiple classes. Maybe you can add a `body.pull-to-refresh` class to those pages?

**Comment by nickcom** [comment]
doesn't appear to work for dynamically added classes

**Comment by pateketrueke** [comment]
> doesn't appear to work for dynamically added classes.

Hi, unfortunately it does not work for dynamic classes but you can use DOM elements instead, or just selecting the entire body with no classes:

```js
const instance = PullToRefresh.init({
  mainElement: document.body, // or document.querySelector('body')
});
```

>  I don't understand what is meant by

This can be illustrated as follows:

```js
// calling init() will return an object with a single method: destroy()
const instance = PullToRefresh.init();

// later, you may want to call it
instance.destroy();
```

**Comment by faelsoto** [comment]
Ok, I got you know. I thought you were reloading between pages. As @pateketrueke said, you can destroy it whenever you don't need it. I think it's best to use `shouldPullToRefresh`, which starts the whole process. You can pass a function that evaluates `!window.scrollY && document.body.classList.contains('my-class')`

**Comment by nickcom** [comment]
thanks!
