### ISSUE TITLE
Overflow div with PTR touch based

### ISSUE THREAD

**Issue by genericmilk** [BoxFactura/pulltorefresh.js#25]
Hi there, I have a div with a PTR instance on it. If I use the touch tools in Chrome Dev to drag to scroll, If I've scrolled down a bit, And then try to scroll back up because of the downword pull motion to scroll it triggers the PTR action. Is it at all possible to write a function / fix this so that the PTR action only happens if the current container's scrollpos is at 0 on the y axis? Thanks!

**Comment by pateketrueke** [comment]
Yeah, you can pass a function `shouldPullToRefresh` for handling such cases.

The default function is: `shouldPullToRefresh: () => !window.scrollY` so I think you can improve it to fit your needs.

**Comment by genericmilk** [comment]
Ah my apologies for missing that on the documentation. Cheers!
