### ISSUE TITLE
Refreshing when scrolling

### ISSUE THREAD

**Issue by jtmerch** [BoxFactura/pulltorefresh.js#27]
Hello, is there any way for me to perform the refresh only when I'm at the top of the page?  As it stands the app reloads anytime I try to scroll down on the mobile web app.

Thanks for any help.

**Comment by john-doherty** [comment]
Hi @jtmerch, yes you need to use the `shouldPullToRefresh` property, assign it a function that checks the scrollTop value of your list, returning true if pullToRefresh is allowed, otherwise false:

```js
shouldPullToRefresh: function() {
    return (document.querySelector(listContainerSelector).scrollTop === 0);
}
```

**Comment by faelsoto** [comment]
To make it clearer, [I just updated the demos](https://www.boxfactura.com/pulltorefresh.js/demos/shouldptr.html), please check them out.

**Comment by jtmerch** [comment]
Yeah for some reason it's still refreshing even when I'm at the bottom of the page and try to scroll up.  I think it's something with the web/mobile template that I'm using because when I test the scroll position from the bottom of the page it returns "0" regardless of where I am on the page.  I will try to figure it out but if you have seen this behavior before I would love to hear any recommendations.

**Comment by john-doherty** [comment]
Have you tried getting the element within `shouldPullToRefresh` each time:

```js
shouldPullToRefresh: function() {
    // notice we're not using a cached pointer to the element
    // it queries the DOM each time.
    return (document.querySelector('.list').scrollTop === 0);
}
```

I'm not sure why using a reference in a closure would cause a problem but it did in my case.

**Comment by jtmerch** [comment]
No I'm calling it like this: 

shouldPullToRefresh: function() {
    // notice we're not using a cached pointer to the element
    // it queries the DOM each time.
    return (document.querySelector('.list').scrollTop === 0);
}

I'm calling the content div, not the list because it's not an actual list.  It's a content div, a fixed header, and fixed footer.  So I'm calling "return (document.querySelector('#contentdivid').scrollTop === 0);"

**Comment by john-doherty** [comment]
Have you tried console logging the value within the `shouldPullToRefresh` function?

```js
shouldPullToRefresh: function() {
     console.log(document.querySelector('#contentdivid').scrollTop);
     return (document.querySelector('#contentdivid').scrollTop === 0);
}
```

If so, does it change when you scroll down and then attempt to pull down?

**Comment by jtmerch** [comment]
That's one of the issues.  I'm developing on a device that is not touchscreen.  To test it I have to deploy to my phone and my phone browser doesn't show me a console log.

**Comment by john-doherty** [comment]
You don't need to, you can use Google Chrome developer tools - click the [Toggle device toolbar](https://developers.google.com/web/tools/chrome-devtools/device-mode/) button from within the inspector. 

You might need to refresh the page but it will then use touch events, allowing you to set breakpoints etc.

**Comment by faelsoto** [comment]
@jtmerch perhaps you need to simplify your issue. Create a new page with just the barebones of what you have in your webapp, and then add ptr.js. Maybe it's another thing.

Also, you can share that demo so anybody can check what's wrong.

**Comment by jtmerch** [comment]
Ok thanks for your help.  I'm away now for the evening.  I will try to look at it when I get back in.  Thanks again!

**Comment by jtmerch** [comment]
I did get it to work, I added to a div just above the div that I've been trying and it seems to work fine now.  Thanks for your help!  Really cool plugin!

**Comment by faelsoto** [comment]
Glad it worked for you!
