### ISSUE TITLE
Shouldn't the touch listeners be hooked to the trigger element rather than window?

### ISSUE THREAD

**Issue by h77ps** [BoxFactura/pulltorefresh.js#28]
I ran into an issue where I have 2 lists side by side, one with pull to refresh one without. When the list with pulltorefresh is sitting at the top of it's scroll the second list wont respond to scroll up. Digging deeper I saw that the events for touch are wired to the window object so that is causing the problem. If I hook the eventlisteners to the triggerelement it works as expected.

**Comment by faelsoto** [comment]
The trigger is on body, because it's the intended behavior: to drag anything on the page to start the refresh. However, this is just the default behavior, and there's a setting for your case.

Please take a look at the demos.

**Comment by h77ps** [comment]
Thank you for the quick response! The trigger is on body by default and it can be swapped with w/e element is passed as trigger and that works well. However in the code the touch events are still attached to the window object like so: ` window.addEventListener('touchend', _onTouchEnd);`. In the _onTouchMove the touch event is prevented since shouldPullToRefresh condition from the first list is satisfied. I've looked at the other options and demos and can't seem to find one that lets the touch event go for other lists on the same page. Any tips?

**Comment by h77ps** [comment]
To illustrate my issue I've made a jsfiddle. Please excuse the ugly code. There are 2 lists, the one on the left has pull to refresh the one on the right does not. When used on a touch enabled device you'll see that the second list is unable to scroll up (the scroll is not effected on mouse wheel, only on touch)

Here is the link: https://jsfiddle.net/pajgnxay/

**Comment by pateketrueke** [comment]
Hi, thanks for your feedback and the fiddle, and yeah... this is an issue.

For sure the default event behaviour should not prevent any other trigger, just the focused one.
