### ISSUE TITLE
Customize the look

### ISSUE THREAD

**Issue by orck-adrouin** [BoxFactura/pulltorefresh.js#29]
Hello,

is it possible to customize the look of `pulltorefresh.js`? I like this library and it works very well, however I would like to have more of an Android look (see screenshot below) for a progressive web app that I am developing.

![image](http://i.imgur.com/PtY0Ju1.gif)

**Comment by faelsoto** [comment]
That's in our roadmap, however there's no branch for it. Maybe you contribute by starting it?

**Comment by orck-adrouin** [comment]
I was able to achieve the look I wanted by heavily customizing the styles and using a rotating svg element for instructionsPullToRefresh.

**Comment by pateketrueke** [comment]
Additionally you can use the options `getMarkup` and `getStyles` for custom templating and such.

Both options should be functions and must return html/css respectively, I think is better than heavely override the css.

Of course, it would be helpful to know how you did it.

**Comment by orck-adrouin** [comment]
This is what I meant by 'overriding the css'.

**Comment by orck-adrouin** [comment]
I forgot to attach the image...

![ptr-android](https://user-images.githubusercontent.com/16353378/30440155-b7f16580-9943-11e7-8329-6fffb7acdc9a.gif)

**Comment by akash-pal** [comment]
please share your entire code.
