### ISSUE TITLE
how to make multiple instance

### ISSUE THREAD

**Issue by mike8625** [BoxFactura/pulltorefresh.js#31]
if multiple div need pull refresh, how to do?  it doesnt work on multiple element in one page.

` 
    <div id="main">
        <button id="test" onclick="test1();">test</button>
        <button id="test" onclick="test1();">test</button>
        <button id="test" onclick="test1();">test</button>
        <button id="test" onclick="test1();">test</button>
        <div>dsfsd</div>
        <div>dsfsd</div>
        <div>dsfsd</div>
        <div>dsfsd</div>
        <div>dsfsd</div>
        <div>dsfsd</div>
        <div>dsfsd</div>
        <div>dsfsd</div>
    </div>
    <div id="main2">
        <button id="test" onclick="test1();">test</button>
        <button id="test" onclick="test1();">test</button>
        <button id="test" onclick="test1();">test</button>
        <button id="test" onclick="test1();">test</button>
        <div>dsfsd</div>
        <div>dsfsd</div>
        <div>dsfsd</div>
        <div>dsfsd</div>
        <div>dsfsd</div>
        <div>dsfsd</div>
        <div>dsfsd</div>
        <div>dsfsd</div>
    </div>
    <script src="js/pulltorefresh.min.js"></script>
    <script>
      PullToRefresh.init({
        mainElement: '#main',
        onRefresh: function() { alert('refresh') }
      });
      PullToRefresh.init({
        mainElement: '#main2',
        onRefresh: function() { alert('refresh') }
      });
    </script>    
`

**Comment by pateketrueke** [comment]
Hi, thanks for your interest in this project!

Unfortunately pull-to-refresh was not designed for multiple instances, however, if you think this feature is worthy I think we can work on a PR soon.

TBH it shouldn't be difficult to achieve, but a major refactor is required to fix this.

**Comment by mike8625** [comment]
Thank you for your help.  I found a way to make "muitiple instances" in one page.  the divs which need pullrefresh are in deffirent tabs,  when i swith the tab, i call PullToRefresh instance "destroy" method in  previous tab,  and set PullToRefresh.init in current tab. and now it work.
My english is not very good , but i am working on it

**Comment by pateketrueke** [comment]
I think your solution is the correct one because tabs are hiding the ptr, and that's ok.

Also... good news! I refactored the main API to support multiple instances. 🎉 

Check out the related example: [multiple instances](https://github.com/BoxFactura/pulltorefresh.js/blob/master/demos/multiple.html)

> Just note that both setups set their `mainElement/triggerElement` as the same selector, otherwise if you set only the `mainElement` then `document.body` is used as trigger resulting in unexpected behaviors.

**Comment by mike8625** [comment]
well done :+1:
