### ISSUE TITLE
Cant work with cordova android

### ISSUE THREAD

**Issue by hdminh247** [BoxFactura/pulltorefresh.js#38]
On android platform with  cordova app, if user scroll from bottom to top, only touch start and only 1 touch move event is called, no touch end is fired.
This causes pull state is stuck at 'pulling' event and it doesnt work until user tap once on screen again to trigger touch end event

**Comment by faelsoto** [comment]
This issue might be related to how Cordova handles touch events, and as ptr.js is focused on the web platform and it's working correctly, you might need to debug the differences between Cordova and a browser on how touch events are handled.
