### ISSUE TITLE
I built a Firefox extension! Can I use your icon? :D

### ISSUE THREAD

**Issue by andreicristianpetcu** [BoxFactura/pulltorefresh.js#40]
Hello,
2 minutes ago I built a Firefox extension that injects on Android on all pages your JS script and it is AWESOME!!! I'm working on a name and icon now. The addon is still unlisted.

Can I use them from your site or should I pick a name/icon for myself? Can I remix your icon?

Regardless of your answer I will give credit where credit is due :D 
I will publish my addon as Free Software on GitHub. Will link it from here.

People over at https://bugzilla.mozilla.org/show_bug.cgi?id=1162150 will be very happy :D 

Thank you again for building this awesome JS library :D

**Comment by andreicristianpetcu** [comment]
Nevermind.... I made my own icon :D https://addons.mozilla.org/en-US/firefox/addon/firefox-pull-to-refresh/

https://github.com/andreicristianpetcu/firefox_pull_to_refresh

**Comment by faelsoto** [comment]
Hey, great work!

As a fellow Firefox Mobile user, this shows one of the many benefits about Firefox on your phone—you can do almost anything!

Regarding the icon, everything is open source! I've been building stuff for more than half my life and everything is thanks to open source, so this is one way of saying thanks.
