### ISSUE TITLE
[Firefox] Bug in the "Should pull to refresh?" demo

### ISSUE THREAD

**Issue by ThibaultVlacich** [BoxFactura/pulltorefresh.js#43]
On Firefox, there is a bug on the "Should pull to refresh?" demo.

Clicking on the checkbox triggers the pull to refresh. Here's a video showing the bug: https://streamable.com/mbpcg

I am not keeping the mouse button pressed, I just click one time on the checkbox.
Tested on Chrome also, and the bug do not seem to be there.

**Comment by faelsoto** [comment]
That totally is because we're including the touch emulator by hammer.js because a lot of folks are missing that these pages are meant to be used on mobile.

Maybe we'll have to remove the emulator.

Anyway, thanks for the heads up!
