### ISSUE TITLE
Not be able to slide down and report wrong

### ISSUE THREAD

**Issue by jeely919** [BoxFactura/pulltorefresh.js#47]
When fingers slide up, they will not be able to slide down and report wrong (Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted)

I need your help, thank.

**Comment by faelsoto** [comment]
I'm sorry, I don't understand. Could you provide more information, code and a use case?

**Comment by yglodt** [comment]
I think this is the same issue than #61

**Comment by sturm3nta** [comment]
This can be helpful: `shouldPullToRefresh: () => !window.scrollY,`
