### ISSUE TITLE
Windows Edge support

### ISSUE THREAD

**Issue by dweber019** [BoxFactura/pulltorefresh.js#48]
I'm evaluating a pull to refresh library and saw this library.

As a requirement we also have to support Windows Edge which is currently not working.

Tested with Edge 42.

It there any intention to support Edge in the future?

**Comment by pateketrueke** [comment]
Hi @dweber019 , it's an interesting case.

IMHO if our users wants this happen I'm OK with that.

> It there any intention to support Edge in the future?

I'm not Windows user and doing such integration is not easy on my side, but we're open to PR if they solve this problem. Of course I can try if I get some spare time soon.

Thanks for your feedback!

**Comment by faelsoto** [comment]
It's currently working on Edge 42, I just tested it.
