### ISSUE TITLE
Issue with testem / Chrome in tests

### ISSUE THREAD

**Issue by DanielRuf** [BoxFactura/pulltorefresh.js#52]
It seems it is not properly configured and npm auto-updated the dependencies (this is why we should use package-lock.json and `npm ci`).

https://travis-ci.org/BoxFactura/pulltorefresh.js/builds/425531162

**Comment by pateketrueke** [comment]
Thanks for your feedback, CI is stable now: https://github.com/BoxFactura/pulltorefresh.js/pull/51

Now just waiting for some feedback before proceed.
