### ISSUE TITLE
Manually fire event

### ISSUE THREAD

**Issue by john-doherty** [BoxFactura/pulltorefresh.js#53]
Is there a way to manually fire pull to refresh, rather than waiting for the user? I'm thinking of a UX use case, so the user opens a list and sees it refreshing, therefore is aware of it's existance

**Comment by faelsoto** [comment]
If you check out the [demos](https://www.boxfactura.com/pulltorefresh.js/demos/basic.html), we're including a touch emulator on desktop. You can check out its source code to figure out how to trigger it manually.

Or check out the JS Event API.
