### ISSUE TITLE
CSS and Starting Height

### ISSUE THREAD

**Issue by baltringer** [BoxFactura/pulltorefresh.js#56]
Not really an issue but the creator told me to comment and I'm new here so this is the only space I can find. Please direct me elsewhere if It needs to live in a different section.

1. I am trying to change the color of the text for the pull down to black or white depending on the page.
2. I need to adjust the starting height of the pull down so that it starts at my App header (right now it hides underneath it. 

any help on these two things would be amazing

**Comment by faelsoto** [comment]
Hello @baltringer, custom CSS is not supported yet. However you can overwrite the values via CSS or via the included scss file.

**Comment by baltringer** [comment]
Sorry I couldn't figure out what css selectors I needed to change it. Can you give me some tips? 

Also how do I set the start poison for the pull down? If I have a fixed header?

**Comment by faelsoto** [comment]
@baltringer I'm sorry, we can't provide support for every customization needed. However we can quote you a few hours of develpment if you need it, else you'll have to figure it out.

**Comment by baltringer** [comment]
Do you have a ton of people asking about this project right now? 

Bummer, are there forums that discuss your project somewhere where I can learn more about how it works?

**Comment by faelsoto** [comment]
Have you tried StackOverflow? Also you can take a look at the source code.
