### ISSUE TITLE
Pulltorefresh crash if you destroy it while working

### ISSUE THREAD

**Issue by plmarko** [BoxFactura/pulltorefresh.js#57]
I'm using the pulltorefreshjs in the react app.

Problem: It is not intit correctly again if you  destroy it  while working (The top refrshing bar is showing).

My environment:
React:16.3
Browser: Chrome

The example code:
```
import React from 'react';
const PullToRefreshJS = require('pulltorefreshjs');


class SomeList extends React.Component {
  constructor(props){
    super(props);
  }
  componentDidMount(){
    this._refreshEngine = PullToRefreshJS.init({
      onRefresh: function() {
        //do some action
      },
      shouldPullToRefresh: () => {
        return !document.body.querySelector(options.mainElement).scrollTop;
      },
      ...options,
    });
  }
  componentWillUnmount(){
    this._refreshEngine.destroy();
  }
}
```
 
In the above scenario SomeList component unmounting and destroy pulltorefreshjs. When you  unmount the SomeList component quickly while pulltorefreshjs is still working you cannot init pulltorefreshjs correctly again. 
The pulltorefresh is initialized again (see componentDidMount) but the onRefresh method is not called any more. I have to close the app and restart it again to make it work.

What do you suggest to make it work ?
  
Thank you in advance. 
Mariusz

**Comment by faelsoto** [comment]
I'm not familiar with react, but perhaps you could wait until the refresh is done before destroying it. Also depending on it use you could create it within the app and not component-based, and disabling it whether a component needs it or not.

The third option is to modify the destry behaviour, so create a PR if you have some ideas.

**Comment by plmarko** [comment]
Hello, 

I think I found the cause.  Inside pulltorefresh.js there is _shared object which is shared between ptr instances. When the ptr is destroyed in working state the _shared.state is 'refreshing'  and it is left in such state. The init of new ptr do not set _shared.state to default 'pending' and ptr thinks it is still refreshing.  The _shared.state left in 'refreshing' cause that the ptr not working any more.

Adding simple line to the init functioin in pulltorefresh.js solved the problem. Please see below. 

```
init: function init(options) {

      _shared.state = 'pending';



      if (options === void 0) options = {};

      var handler = _setupHandler(options);

      // store offset for later unsubscription
      handler.offset = _shared.handlers.push(handler) - 1;

      return handler;
    },
``` 

In my opinion this _shared object should not be global but rather per ptr instance.

Please suggest your solution to fix it or use mine . 

Thanks for your help. 

Mariusz

**Comment by faelsoto** [comment]
Seems good, could yo create a PR?
