### ISSUE TITLE
the node is not deleted when you release without refreshing

### ISSUE THREAD

**Issue by papattes** [BoxFactura/pulltorefresh.js#58]
Hello, 
if like me you need to delete the ptr node when you start pulling down without refreshing, in the source file, in the _onTouchEnd () function, modify:

`function _onTouchEnd() {
      if (!(_el && _el.ptrElement && _shared.enable)) {
        return;
      }

      if (_shared.state === 'releasing' && _shared.distResisted > _el.distThreshold) {
        _shared.state = 'refreshing';

        _el.ptrElement.style[_el.cssProp] = (_el.distReload) + "px";
        _el.ptrElement.classList.add(((_el.classPrefix) + "refresh"));

        _shared.timeout = setTimeout(function () {
          var retval = _el.onRefresh(function () { return _ptr.onReset(_el); });

          if (retval && typeof retval.then === 'function') {
            retval.then(function () { return _ptr.onReset(_el); });
          }

          if (!retval && !_el.onRefresh.length) {
            _ptr.onReset(_el);
          }
        }, _el.refreshTimeout);
      } else {
        if (_shared.state === 'refreshing') {
          return;
        }
        _el.ptrElement.style[_el.cssProp] = '0px';

        _shared.state = 'pending';
	_ptr.onReset(_el); // add this here
      }

      _ptr.update(_el);

      _el.ptrElement.classList.remove(((_el.classPrefix) + "release"));
      _el.ptrElement.classList.remove(((_el.classPrefix) + "pull"));

      _shared.pullStartY = _shared.pullMoveY = null;
      _shared.dist = _shared.distResisted = 0;
    }`

**Comment by faelsoto** [comment]
Thanks for your input, could you please create a PR?
