### ISSUE TITLE
Problems with preventDefault

### ISSUE THREAD

**Issue by marcus13371337** [BoxFactura/pulltorefresh.js#61]
Hello,

This plugin spits out a lot of errors in my console. IF I don't enable passivemode I get:
`[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

If I enable passive mode I get the following:
`Unable to preventDefault inside passive event listener invocation.`

I think you should never try to prevent a touchmove event...

**Comment by faelsoto** [comment]
Those are not errors, are warnings. I agree with what you're saying, but we haven't found another way to make it work. If you do, please consider opening a PR.

**Comment by yglodt** [comment]
Unforntulately, at least for me, these errors make scrolling feel "hard" and unresponsive.

**Comment by faelsoto** [comment]
@yglodt we have investigated and we are unable to reproduce the issue, please open a bug report so we can look into it.

**Comment by sturm3nta** [comment]
This can be helpful: `shouldPullToRefresh: () => !window.scrollY,`
