### ISSUE TITLE
When I scroll down,i it will refresh.

### ISSUE THREAD

**Issue by xj001** [BoxFactura/pulltorefresh.js#62]
` var ele = document.querySelector("#wrapper")
	   PullToRefresh.init({
      mainElement:"#wrapper",
      shouldPullToRefresh: function() {
        return (ele.scrollTop === 0);
      }
    })`
I have tried set shouldPullToRefresh,but it don't work

so,I tried another way 

`handleScroll:function (event) {
		  console.log(event.touches);
      var hei = event.touches[0].pageY;
      console.log(hei < window.screen.height);
        PullToRefresh.init({
          mainElement:"#wrapper",
         shouldPullToRefresh:function(){
           return(hei < window.screen.height )
         },
          instructionsPullToRefresh:"下拉刷新",
          instructionsRefreshing:"正在刷新中"
        })
    },`
`window.addEventListener("touchstart",this.handleScroll,true)`

when it was false and I pull down, It still refresh. my phone screen can not be pulled down and then ,it refresh

**Comment by pateketrueke** [comment]
Could you provide more information?

I mean, this library should work in major browsers, even its main target is mobile.

If you provide information would be helpful to understand, also you can create a public fiddle to see how your code is working in your phone so we can also check that.

**Comment by faelsoto** [comment]
I'm closing this issue because we aren't able to provide support. Please refer to the docs and examples.

If you still experience some issues, please create a PR with a test case so we can investigate it.
