### ISSUE TITLE
Version 0.1.16 breaks scrolling downwards in Chrome

### ISSUE THREAD

**Issue by konstantin-vassiliev** [BoxFactura/pulltorefresh.js#64]
Init code:
```
    window.PullToRefresh.init({
      mainElement: 'body',
      distThreshold: 100,
      distMax: 120,
      distReload: 1,
      iconArrow: '<i class="fa fa-arrow-down"></i>',
      iconRefreshing: '<i class="fa fa-spin fa-refresh"></i>',
      instructionsPullToRefresh: rmx.localize('System.Pull'),
      instructionsReleaseToRefresh: rmx.localize('System.Release'),
      instructionsRefreshing: ' ',
      refreshTimeout: 250,
      onRefresh: function () {
        $(document).trigger('vm.load');
      },
      onInit: function () {
        document.addEventListener('touchstart', onTouchListener);
        document.addEventListener('touchmove', onTouchListener);
      }
    });
```
Running Chrome 71.0.3578.98 on MacOs 10.14

Version 0.1.15 works fine.

**Comment by faelsoto** [comment]
Could you create a JSFiddle? Your snippet is not that helpful.

**Comment by pateketrueke** [comment]
@konstantin-vassiliev  where are you defining `onTouchListener` and what it does? 🤔

**Comment by konstantin-vassiliev** [comment]
@pateketrueke Sorry for absence.

See now I missed an important point: fault arises only on when emulating a mobile unit, guess has something to do with “touch…” events.

Our onTouchListener suppresses event propagation when user is interacting with a range element.

Feel free to reopen the issue. Will try to be more present.

Thank you in any outcome.

**Comment by pateketrueke** [comment]
We use [hammer-touchemulator](https://github.com/BoxFactura/pulltorefresh.js/blob/b8ce09503f9b121db280cff8faa1ae790809a90e/src/_/layout.pug#L50) for doing that on our e2e tests, and without having to touch our library code.

Not sure if I understood, what you're using for simulating mobile?

**Comment by konstantin-vassiliev** [comment]
The fault was discovered on an actual Android unit and confirmed in Chrome dev tools mobile render.

Works on iOs. So only a chrome issue it appears. As mentioned: version 0.1.15 does not experience the same fault.

Regards.
