### ISSUE TITLE
Touch-scrolling broken in 0.1.16

### ISSUE THREAD

**Issue by solojuve1897** [BoxFactura/pulltorefresh.js#65]
# Bug report

**Current behavior:**
Scrolling upwards using touch doesn't work. Tried on laptop with touch-display and on Android-phone. There is no error in the console.

**Expected behavior:**
That scrolling works with touch like previous versions.

**JSFiddle URL for demo with bug:**

**Browsers affected:**
Chrome

There's a closed issue regarding this bug. I created this issue because the bug hasn't been solved and there is no reason to close the isusue.
https://github.com/BoxFactura/pulltorefresh.js/issues/64

**Comment by faelsoto** [comment]
Closed because demo URL is not included
