### ISSUE TITLE
pulltorefresh stops working all together if destroyed while running

### ISSUE THREAD

**Issue by solojuve1897** [BoxFactura/pulltorefresh.js#66]
# Bug report

**Current behavior:**
Pulltorefresh stops working all together if destroyed while running. In my setup the issue occurs if the user navigates to another route (navigating destroys pulltorefresh-instances) while pulltorefresh still is working on the users current route. This is in the context of an SPA built with Vue.js. At the moment I have to restart the entire application for pulltorefresh to work again. There is no errors in the console.

**Expected behavior:**
That it gracefully releases held element back to top and upon new init it works again.

**JSFiddle URL for demo with bug:**

**Browsers affected:**
All

There is an issue describing this very behaviour which was supposed to be fixed in 0.1.16 but I still experience this in 0.1.16: https://github.com/BoxFactura/pulltorefresh.js/issues/57

**Comment by faelsoto** [comment]
Closed because demo URL is not included
