### ISSUE TITLE
Slowing / Hanging page white scrolling up

### ISSUE THREAD

**Issue by peterujah** [BoxFactura/pulltorefresh.js#67]
I have just include this in my project it working fine when swipe but while scrolling the page up it will keep hanging but works fine while scrolling down

```
 PullToRefresh.init({
	mainElement: '.PageBodyContainer ',
	shouldPullToRefresh: function() {
		console.log(document.querySelector('#contentdivid').scrollTop);
		return (document.querySelector('.PageBodyContainer').scrollTop === 0);
	},
	instructionsPullToRefresh: '<img src="/ajax-loader.gif"/>',
	instructionsReleaseToRefresh: '<img src="/ajax-loader.gif"/>', 
	instructionsRefreshing: '&nbsp;',
	iconRefreshing: '<img src="/ajax-loader.gif"/>',
	onRefresh: function() { 
		console.info('refresh') 
	}
  });
```

**Comment by faelsoto** [comment]
Please don't delete the template for the issue as it's required for us to see what's happening. The included snippet won't help us at all because we can't see your markup.

**Comment by sturm3nta** [comment]
This can be helpful: `shouldPullToRefresh: () => !window.scrollY,`
