### ISSUE TITLE
Deeply nested elements will not trigger pull to refresh

### ISSUE THREAD

**Issue by xcskier56** [BoxFactura/pulltorefresh.js#7]
If you have a deeply nested dom, (bad idea, I know), it is possible for the function `_closestElement` to fail to find the `triggerElement` as in a parent node of the event.

Since `_closestElement` only walks 10 nodes up the tree, if a node is 11 or more steps away from the refresh container, then pulling down on that element will not trigger the pull to refresh because the function will believe that the target of the `touchStart` is not a child of the refresh container.

I solved this by adding a `lookupDepth` to the options, and passing that into the `_closestElement` function. In my app, after a cursory search, the deepest node is 19-20 deep, and so I set it at 25 just to be safe. This is however, confusing and not intuitive. 

A better solution might be to listen to touch events on the `triggerElement`. I'm not sure of the intricacies of this for cross browser support, but I'd be happy to work on a PR given your feedback and direction.

**Comment by faelsoto** [comment]
Could you create a PR? Maybe the best fix would be to rewrite `_closestElement` to be recursive until the root element.

**Comment by xcskier56** [comment]
Absolutely, I'm happy to. Looking into this more, what do you think of using `node.contains(otherNode)`? Its implemented in all modern browsers, going back to IE5 and does exactly what we're looking to do. To me it seems easier than rebuilding the wheel.


    window.addEventListener('touchstart', (e) => {
      // ...

      const triggerNode = document.querySelector(triggerElement);
      _enable = triggerNode.contains(e.target);

      // ...
    });


To make this more performant, we could store the `triggerNode` in the settings for reuse.
