### ISSUE TITLE
Is there any way to call a function when you've hit the boundary between Pull to Refresh and Release to refresh?

### ISSUE THREAD

**Issue by abulawright** [BoxFactura/pulltorefresh.js#72]
Hiya, sorry this isnt a bug per-say, but I've been using this on my PWA app and was wondering if there is a way to call a function when you've fully scrolled down, as I wanted to add a window.navigator.vibrate. I had a look through your code but I couldn't figure out a simple way to add it, as I'm not that experienced with Javascript.

**Comment by pateketrueke** [comment]
Sorry if we can't solve this for you but also is not ok for us modify our implementation for adding customer-specific behavior.

Just add an event listener to the window, and the check the current scrollTop vs the total height of the document.

Thank you!

**Comment by faelsoto** [comment]
Also, feel free to open a PR if you're willing to put some work on it.

**Comment by pateketrueke** [comment]
@abulawright pardon my previous response, I just wanted to express that this feature is not currently implemented.

> If you want to add that behavior by hand in your application try adding an event listener to the window, and then check the current `window.scrollTop` vs the total height of your document.

So much thanks for your feedback.
