### ISSUE TITLE
not work on mobile

### ISSUE THREAD

**Issue by abdel777** [BoxFactura/pulltorefresh.js#73]
This plugin works fine on browser, but when it comes to mobile devices it behaves weird. When we re on the bottom or middle and want to go up by screen touching the refresh method fire. Do you have any solution for that issue ?

**Comment by pateketrueke** [comment]
> Do you have any solution for that issue ?

It's hard to understand without proper explanation and code.

Please stick to the [ISSUE's template](https://github.com/BoxFactura/pulltorefresh.js/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) and provide enough details to guide us.

Once you have a working fiddle with the code you're using we can try to debug it with our own devices, thank you!

**Comment by faelsoto** [comment]
@abdel777 please use the issue template, otherwise we will be promptly shutting down your issue.
