### ISSUE TITLE
Refresh when i swipe without being on top

### ISSUE THREAD

**Issue by narcisao** [BoxFactura/pulltorefresh.js#74]
I am trying to use this pull to refresh, but im having an issue. I've looked for other issues like this, but didnt found any answer that solve my problem, so I submited this issue. I tried with 0.1.14 and 0.1.17 versions and none worked. My app is built using cordova and i tested both in mobile and browser.

# Bug report

**Current behavior:**
When i scroll, my app refresh.

**Expected behavior:**
My app refresh only its on top.

** for demo with bug:**
https://jsfiddle.net/L4dypo8n/

**Browsers affected:**
Google chrome / android

**Comment by pateketrueke** [comment]
Hello @narcisao so much thanks for your input, however I was not able to run your demo.

**Comment by narcisao** [comment]
https://jsfiddle.net/L4dypo8n/4/ try with this new one. changed the source code from html

**Comment by pateketrueke** [comment]
Did you confirmed it replicates the same issue?

**Comment by narcisao** [comment]
I checked on another computer. For this app, im using cordova. I opened the console and for a reason (that i dont know why) my parameter "window.scrollY" is ALWAYS 0, so, when PTR calls the function "shouldPullToRefresh" the answer is TRUE, even if im not at the top of screen. Any sugest?

**Comment by pateketrueke** [comment]
Try providing your own `shouldPullToRefresh()` function in order to see why `window.scrollY` is always zero, there you can test other props on window (cordova-specific may be?) to see of any works for you.

**Comment by faelsoto** [comment]
I'm closing this issue, the JSFiddle is not working and therefore we aren't able to reproduce the issue. Please feel free to open another issue making sure the JSFiddle is working, as well as testing it on web and mobile browsers.

**Comment by narcisao** [comment]
Thanks for the help guys. :)
