### ISSUE TITLE
Each time calling PullToRefresh.destroyAll create new dom node

### ISSUE THREAD

**Issue by xu33** [BoxFactura/pulltorefresh.js#75]
# Bug report

**Current behavior:**

Each time calling PullToRefresh.destroyAll create new dom node

**Expected behavior:**

Don't create new dom node.

**JSFiddle URL for demo with bug:**

**Browsers affected:**

**Comment by pateketrueke** [comment]
Please, fulfill all the required details before opening an issue. 👮 

Ir very hard to understand what's wrong without proper code, once you've done I'll re-open it.

**Comment by xu33** [comment]
> Please, fulfill all the required details before opening an issue. 
> 
> Is very hard to understand what's wrong without proper code, once you've done I'll re-open it.

I have filled up the required area,please take a look when you have time,thank you very much.

**Comment by faelsoto** [comment]
Everything is required, you just filled two of the four inputs we're requiring.

**Comment by faelsoto** [comment]
@xu33 the issue you're reporting it's the default behaviour, we haven't had any issues with it.

You could do one of these things:

1. Leave the element there, it won't affect anything as its size is 0
2. Destroy it manually, in your demo you're already accessing it
3. Open a PR suggesting the new behaviour
