### ISSUE TITLE
0.1.19 is buggy in iOS

### ISSUE THREAD

**Issue by badtant** [BoxFactura/pulltorefresh.js#82]
0.1.18 works nice but when I upgraded to 0.1.19 the refresh wants to start directly when I start scrolling up. it doesn't wait until I've reached the top and continues to scroll.

**Comment by pateketrueke** [comment]
Yes, we changed the defaults for `shouldPullToRefresh` so in order to implement the old behaviour you should re-define this function:

https://github.com/BoxFactura/pulltorefresh.js/blob/bf9ab09ff810fa0e000c25033353684848b793e2/src/lib/defaults.js#L25-L29

**Comment by badtant** [comment]
thank!
