### ISSUE TITLE
Update definitly typed version

### ISSUE THREAD

**Issue by jeanpoelie** [BoxFactura/pulltorefresh.js#85]
Can you update your definitly typed version so that it includes the new property distIgnore?

[DefinitlyTyped Library](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41442)

**Comment by faelsoto** [comment]
I'm sorry, I'm not understanding what's the request, nor what is DefinitelyTyped.

**Comment by jeanpoelie** [comment]
DefinitlyTyped is a npm packaging library that has typescript typed definition files so that people who use react can use other libraries than only typescript libraries. Your library is an amazing extension for a lot of apps, but unfortunatly the .d.ts file is missing certain properties.

**Comment by faelsoto** [comment]
Oh, I see. But rather than opening an issue I think you could contribute by creating a PR, could you do that?
