### ISSUE TITLE
Cannot read property 'classList' of null within onReset()

### ISSUE THREAD

**Issue by johnysusanto** [BoxFactura/pulltorefresh.js#87]
# Bug report

**Current behavior:**
We're getting errors Cannot read property 'classList' of null via our Sentry and it traces down to 
/node_modules/pulltorefreshjs/dist/index.umd.js in onReset at line 72:24

**Expected behavior:**
Should check if element exist before proceeding with the function's process
<img width="671" alt="Screen Shot 2020-02-18 at 2 57 39 pm" src="https://user-images.githubusercontent.com/811855/74715465-09eb2e80-525f-11ea-8c1c-78c4d75107f4.png">

**JSFiddle URL for demo with bug:**

**Browsers affected:**

**Comment by pateketrueke** [comment]
Got it, which version you're using?

**Comment by faelsoto** [comment]
@johnysusanto all fields are required, especially the JSFiddle URL so we can debug it. Feel free to open another issue and be sure to complete every piece of data required.

**Comment by johnysusanto** [comment]
> Got it, which version you're using?

It's the latest one.

> @johnysusanto all fields are required, especially the JSFiddle URL so we can debug it. Feel free to open another issue and be sure to complete every piece of data required.

It happens randomly so it's quite hard for us to replicate this. But looking at the Sentry log, I think the fix location should be quite obvious

Thank you

**Comment by pateketrueke** [comment]
Yeah, may be there is a race condition in your code but according our tests those are covered. If something happens at implementation level is hard to actually understand without enough context.

Having a minimal reproducible example that demonstrate the issue is the right way to begin.
