### ISSUE TITLE
How to display Pull To Refresh in overscroll Safari

### ISSUE THREAD

**Issue by vukhacbiet** [BoxFactura/pulltorefresh.js#89]
When use scroll (touch) down and scroll up immediately in Safari (iOS device), it not detect should 'pull to refresh' and don't show the pull to refresh div.

How can handle overscroll and show pull to refresh when user do it.

Thank you

**Comment by pateketrueke** [comment]
Hi @vukhacbiet please fulfill the template we have for bug report, anything without enough detail to follow up will be closed otherwise. Thank you!

**Comment by vukhacbiet** [comment]
![ezgif-2-90818bf07edd](https://user-images.githubusercontent.com/43400653/82011645-ce1a0680-969f-11ea-9fa1-0357c7bff1bc.gif)

Please see this demo in iPhone simulator

If we start to swipe down, everything will be ok, but when swipe up and down, iOS have a bounce and we can not pull to refresh right here.

**Comment by faelsoto** [comment]
I'm closing this issue because we need a demo URL.

**Comment by vukhacbiet** [comment]
http://www.boxfactura.com/pulltorefresh.js/demos/raw.html

Your demo, and iOS Safari.

**Comment by crusy** [comment]
> http://www.boxfactura.com/pulltorefresh.js/demos/raw.html
> 
> Your demo, and iOS Safari.

Sorry to slide in, but out of curiosity I just tested on iOS 13.4.1 @ iPhone 8 (real device, no simulator), and it is working. However, and I guess that's what happening here, one has to _release the finger_ and wait until Safari has finished the "bounce" effect. Which makes sense: While "scroll" is in progress, "pull" is not possible.

**Comment by vukhacbiet** [comment]
> > http://www.boxfactura.com/pulltorefresh.js/demos/raw.html
> > Your demo, and iOS Safari.
> 
> Sorry to slide in, but out of curiosity I just tested on iOS 13.4.1 @ iPhone 8 (real device, no simulator), and it is working. However, and I guess that's what happening here, one has to _release the finger_ and wait until Safari has finished the "bounce" effect. Which makes sense: While "scroll animation" is in progress, "pull" is not possible. Edit: Don't know if the simulator behaves identically in that point

Everything went wrong when we scroll down and up again (in a gesture)

**Comment by faelsoto** [comment]
Yeah, I'm sorry, it's not only the demo URL, we need additional information, that's why we created a template. Please use it.

**Comment by FrankyXie** [comment]
any luck? any progress? @vukhacbiet
