### ISSUE TITLE
Page scroll up (swipe down) doesn't work in Chrome

### ISSUE THREAD

**Issue by wbreadtn** [BoxFactura/pulltorefresh.js#92]
# Bug report

**Current behavior:**
Scroll page content down via swipe up
Release mouse/touch
Mouse down/touch again
Attempt to scroll up via swipe down (without *any* upward movement)
Page content does not move/scroll
Note - You can circumvent the issue by doing a tiny move upward, then without lifting, continue downward swipe to scroll content up.
**Expected behavior:**
Should scroll without up/down gymnastics
**JSFiddle URL for demo with bug:**

**Browsers affected:**
Using Windows / Chrome version 84.0.4147.125, DevTools "Toggle Device Toolbar" (various devices)
...and Chrome on Android (not sure what version)

**Comment by faelsoto** [comment]
Closed because it was not provided an demo URL in which we can see the issue.
