### ISSUE TITLE
React js Support

### ISSUE THREAD

**Issue by b3of** [BoxFactura/pulltorefresh.js#93]
The [Demo on codesandbox.io](https://codesandbox.io/s/21o9z8rrzy) of React js doesn't exists

I tried to implement it [here on codesandbox.io](https://codesandbox.io/s/pulltorefresh-reactjs-lrdc5) but it doesn't do anything

Is there any other dependency that needs to be installed?

Thanks.

**Comment by faelsoto** [comment]
I'm sorry, this is not a support forum. Please refer to the basic examples and start from there. Also, if you make it work feel free to include the new source code.
