### ISSUE TITLE
Use With React docs demo 404ing

### ISSUE THREAD

**Issue by hllewelyn** [BoxFactura/pulltorefresh.js#94]
# Bug report

**Current behavior:**
Click on the "Demo on codesandbox.io" link in the readme and it 404s

**Expected behavior:**
Click on the "Demo on codesandbox.io" link in the readme and it takes you to a valid demo

**JSFiddle URL for demo with bug:**
N/A

**Browsers affected:**
N/A

**Comment by faelsoto** [comment]
Thanks for reporting it, altough the example was provided via a pull request. Maybe we'll look into deleting it.

If you want to contribute a react demo, feel free to create a PR.
