### ISSUE TITLE
Allow multiple case in shouldPullToRefresh? 

### ISSUE THREAD

**Issue by qlur** [BoxFactura/pulltorefresh.js#99]
# Bug report

**Current behaviour:**
Doesn't work when there are multiple conditions to fulfil. For an instance, I don't want to trigger pull to refresh when on certain elements

My current shouldPullToReferesh looks something like this: 

```  shouldPullToRefresh: function(){
      return ( (!window.scrollY || !document.querySelector("#overlay") || !document.querySelector(".stylesheet-wrapper") || !document.querySelector("#contexttopRight") ||!document.querySelector("body.disable-scroll")  || !document.querySelector(".dndod-wrapper") || !document.querySelector(".dndod-popup")))
    }
```

**Expected behaviour:**
shouldPullToRefresh doesn't work and continue to refresh when pulled from anywhere in the screen. 

**JSFiddle URL for a demo with the bug:**

**Browsers affected:**
Chrome, Safari, Firefox

**Comment by faelsoto** [comment]
Closing it as no demo URL was provided.
